# Generated by Django 2.1.3 on 2018-11-26 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('seccion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('activo', models.BooleanField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coevaluaciones.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='integrantes',
            field=models.ManyToManyField(to='coevaluaciones.Usuario'),
        ),
        migrations.AddField(
            model_name='curso',
            name='ramo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coevaluaciones.Ramo'),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('ramo', 'anno', 'semestre', 'seccion')},
        ),
    ]
