# Generated by Django 2.1.3 on 2018-11-21 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('seccion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField()),
                ('password', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('tipo_usuario', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='alumnos',
            field=models.ManyToManyField(related_name='lista_alumnos', to='coevaluaciones.Usuario'),
        ),
        migrations.AddField(
            model_name='curso',
            name='auxiliares',
            field=models.ManyToManyField(related_name='lista_auxiliares', to='coevaluaciones.Usuario'),
        ),
        migrations.AddField(
            model_name='curso',
            name='ayudantes',
            field=models.ManyToManyField(related_name='lista_ayudantes', to='coevaluaciones.Usuario'),
        ),
        migrations.AddField(
            model_name='curso',
            name='codigo_ramo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coevaluaciones.Ramo'),
        ),
        migrations.AddField(
            model_name='curso',
            name='profesores',
            field=models.ManyToManyField(related_name='lista_profesores', to='coevaluaciones.Usuario'),
        ),
    ]
